### ISSUE TITLE
Add session selection to Nedit booking modal

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#14]
In the Add/Edit New Booking modal, the start and end time selectors must be replaced with the available sessions from the selected service.

We can do this by implementing a mini-wizard:

1. Show a blank (disabled) calendar under the "Services" dropdown, replacing the start and end times.

2. Once a service is selected, populate that calendar with the available days. 

3. Once a day is selected from the calendar, display the available times for that day beneath the calendar.

4. The user can then select an available time for that day.

As a result, the left column of this modal will continue to show the "Duration" field beneath the date and time selectors, but the "Add Notes" field should remove to the right column, beneath "Actions".

**Comment by markzahra** [comment]
Attached are mockups of what the booking modal should do with these changes.

![backend_new_booking_wide-view_service_details-select-date](https://user-images.githubusercontent.com/22813210/40484684-c3dfe71a-5f5c-11e8-83c6-6fbcb6e232d1.jpg)
![backend_new_booking_wide-view_service_details-select-time](https://user-images.githubusercontent.com/22813210/40484687-c400d18c-5f5c-11e8-9276-fed1994fce13.jpg)

Please note that they is not pixel-perfect, only a representation.

**Comment by romalytvynenko** [comment]
Implemented in https://github.com/RebelCode/bookings-js/pull/22

**Comment by markzahra** [comment]
Roman moved this back to Accepted in the GItHub Project as it was moved back to UAT automatically by GitHub earlier on.
