### ISSUE TITLE
Bookings disappearing from calendar after using search

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#15]
### Problem
On bookings page, after searching for something, pressing `enter`, then cleaning search field and pressing `enter`, bookings disappear from calendar and from list.

### Steps to reproduce
- Open bookings list page.
- Type something in `search` field and press `enter`. You will see that bookings are filtered.
- Now delete text from `search` field and press `enter`.
- All bookings are not appeared in list (or in calendar).

### Reason
After cleaning `search` field, front-end application send empty string as a `search` parameter on server. Server doesn't return bookings in this case.

### Possible Solution
Don't sent empty `search` string on serve, removing it from search parameters if it is empty right before sending.

**Comment by XedinUnknown** [comment]
While true, I also thought that we decided there should be a de-bounce, coupled with a minimal number of characters required for a search to be performed. Is this off the table now?

**Comment by romalytvynenko** [comment]
We don't perform search on input. So user press `enter` or submit button and after that we perform search. So we don't need debounce there.

**Comment by XedinUnknown** [comment]
I still think there should be a search on input, and a de-bounce, but this is up to @markzahra. From my side, I would like to confirm whether a minimal about of chars limitation is still something we should be doing. What I mean is that, instead of just checking if the field is empty, you would check if it has `N` characters. And if not, perform the default action.

**Comment by romalytvynenko** [comment]
We decided that we are we are using WP's UX patterns when it is possible. So in Wordpress there are no search on input on posts or pages page, so this why we are not doing it here.

**Comment by XedinUnknown** [comment]
And again, that doesn't answer my question about minimal search string length.

**Comment by XedinUnknown** [comment]
@romalytvynenko does not think that min search string length should be applicable here.

**Comment by XedinUnknown** [comment]
During a call between myself, @markzahra, and @romalytvynenko, we agreed to leave things as is for now.
