### ISSUE TITLE
Cannot change booking status

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#16]
## Symptoms
In edit booking modal, it is not possible to change the existing bookings status, such as from "Scheduled" to something else.

## How to reproduce
- Create new booking
- Open that booking
- Select some change status action in booking modal
- Press "Save"
- Observe symptom

## Cause
For setting new booking status, the client must send transition name, not new booking status name. Now the client is sending status name which sent as `transition`, but there is no transition with that name.

## Recommended Solution
Use transition map from backend instead of hardcoded client's status -> status map. Each action in UI will correspond to transition which will simplify what data should be sent.

**Comment by XedinUnknown** [comment]
Is this issue or the resolving PR related to another issue?
