### ISSUE TITLE
Booking options metabox isn't loading on download nedit page

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#24]
### Symptom
After opening Download edit page booking meta box is not loaded correctly (only markup from templates) and following error appears in console:
> TypeError: undefined is not an object (evaluating 'e.state.endpointsConfig.sessions')

### Steps to reproduce
- Open download's page (new download or edit).
- Observe symptom.

### Reason
`SessionApi` instance is passed to session picker component's factory, which is executed on application start. `state.endpointsConfig.sessions` is passed to session api and it is not present on download's edit page, because api is not used there.

### Possible solution
Check that  `endpointsConfig` presents in state, if not, pass empty object.

**Comment by XedinUnknown** [comment]
Didn't understand how to reproduce. Does the symptom always present on that page?

**Comment by romalytvynenko** [comment]
@XedinUnknown , yes, it is always there.

**Comment by XedinUnknown** [comment]
Fixed.
