### ISSUE TITLE
Featured image cannot be set to a Download from the Nedit page when EDD Bookings is installed.

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#25]
### Symptom
The browser console show the following error when the "_Set Download Image_" link is clicked:
```
TypeError: _.contains is not a function [media-models.js:1306:11]
```

### Steps to reproduce
- Open download's page (new download or edit).
- Press on "Set Download Image".
- Observe symptom.

### Reason
Lodash write itself to global after loading it from umd build, which causes conflict with underscore.js which is used on page.

### Solution
Use `noConflict()` when creating lodash service in container.

**Comment by XedinUnknown** [comment]
Fixed.
