### ISSUE TITLE
REST API error handling in JS

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#32]
### Problem
In UI, the JS is not doing handling of erroneous REST API responses which results in bad experience.

### Solution
User should be notified about REST API errors. In one case, on bookings page, user should see floating error message (notification), in other cases (forms) we should show inline errors.

### Example of bad UX
For example: in the booking modal, if a client is being created with an email that is already assigned to an existing client, the REST API returns a `409 CONFLICT` response. The JS however does not handle this error, showing no message. It just keeps playing the loading animation on the submission button.

Another instance is when an error occurs in the booking modal after submitting it (saving, scheduling, etc.). The modal can sometimes show the error and then immediately closes, but it should stay open to allow the user to see the error message.

**Comment by markzahra** [comment]
@romalytvynenko booking transition errors all use one generic error message, as shown in the screenshot below? In this case, the booking could not be transitioned to Completed as the time of the booking has not passed yet.

<img width="858" alt="screen shot 2018-06-11 at 18 31 26" src="https://user-images.githubusercontent.com/22813210/41244588-c5344ef6-6da5-11e8-86b1-79e8b515c28f.png">

**Comment by mecha** [comment]
I don't think the error messages are related to @romalytvynenko's work. They are sent as error messages from the REST API and show as-is on the front-end.

Given that for any REST API consumer these error messages aren't very helpful, I think it makes more sense to change them in the REST API.

I would keep this issue closed and open an issue in [rebelcode/rcmod-eddbk-rest-api](https://github.com/rebelcode/rcmod-eddbk-rest-api).

**Comment by markzahra** [comment]
@mecha can the REST API present different error messages based on the situation at hand?

If so, go ahead and open that issue in that repo and we will work on the wordings for a future Beta or official release.

**Comment by XedinUnknown** [comment]
I was under the impression that the REST API already gives reasons for failed transitions. @mecha, did I misunderstand something?

**Comment by markzahra** [comment]
This issue will remain closed and be Accepted, in favour of opening one in the [rebelcode/rcmod-eddbk-rest-api](https://github.com/rebelcode/rcmod-eddbk-rest-api) repo, since the different errors to be displayed in the UI are being handled by the REST API.

**Comment by mecha** [comment]
@XedinUnknown There is handling for validation failure exceptions. Most likely this error does not come from such an exception. We should probably discuss this in the REST API module issue. I will be opening one shortly and mentioning you.
