### ISSUE TITLE
Calendar renders availabilities wrong due to daylight saving

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#36]
### Symptom
Setting a week long availability to repeat every week for 40 weeks starts to skip the 7th day in November 2018.
Screencast: http://recordit.co/7Pr45NZCNv

### Steps to reproduce
- Go to the download NEdit page
- Create 7 days availability, all day, that ends on December
- Go to November
- Notice, that availability is 6 days long after October 28th

### Reason
Daylight savings ends on 28th October, and the first repetition that displays the symptom has the 18th October in the middle of it.

### Possible solution
Ignore timezone in calendar, so daylight saving will be not applied to event length.

**Comment by markzahra** [comment]
I can still reproduce this issue in Alpha 9. Screenshots attached.

<img width="882" alt="screen shot 2018-06-11 at 18 22 33" src="https://user-images.githubusercontent.com/22813210/41244227-b527ec26-6da4-11e8-9dd6-3c47986e2363.png">

<img width="658" alt="screen shot 2018-06-11 at 18 22 40" src="https://user-images.githubusercontent.com/22813210/41244226-b5079d54-6da4-11e8-81db-a3575aea8b8b.png">

**Comment by XedinUnknown** [comment]
@romalytvynenko, the title of the issue is way too long. Please change it to something that summarizes the problem, instead of describing the symptom in detail.
