### ISSUE TITLE
Availability editor should work with dates in ISO8601 format

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#5]
Now `start` and `end` is working good, but other dates is not sent in required format which causes unpredictable bugs.

**Comment by markzahra** [comment]
I believe this is now solved, however, can you confirm that ISO 8601 is also used in the repeat option dates? I ask as I saw this in the page source:


<script type='text/javascript'>
--
  | jQuery(document).ready(function(jQuery){jQuery.datepicker.setDefaults({"closeText":"Close","currentText":"Today","monthNames":["January","February","March","April","May","June","July","August","September","October","November","December"],"monthNamesShort":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"nextText":"Next","prevText":"Previous","dayNames":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"dayNamesShort":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"dayNamesMin":["S","M","T","W","T","F","S"],"dateFormat":"MM d, yy","firstDay":1,"isRTL":false});});
  | </script>


Notice the "MM d, yy" on the last line.

If it is unrelated, let me know.

**Comment by XedinUnknown** [comment]
jQuery? That doesn't look like @romalytvynenko's code.

**Comment by romalytvynenko** [comment]
This is not our code, just some WP's code. We can close this task for now.
